/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 .\public\models\WawaOffice.glb
*/

import React, {useLayoutEffect, useRef} from 'react'
import { useGLTF } from '@react-three/drei'
import { gsap } from 'gsap'

export function Office(props) {
    const { nodes, materials } = useGLTF('../../public/models/WawaOffice.glb')
    const ref = useRef();
    const tl = useRef();

    useLayoutEffect(() => {
        tl.current = gsap.timeline();

        tl.current.to(ref.current.position, {duration: 2})

    }, []);

    return (
        <group {...props} dispose={null} ref={ref}>
            <mesh geometry={nodes['01_office'].geometry} material={materials['01']} />
            <mesh geometry={nodes['02_library'].geometry} material={materials['02']} position={[0, 2.114, -2.23]} />
            <mesh geometry={nodes['03_attic'].geometry} material={materials['03']} position={[-1.97, 4.227, -2.199]} />
        </group>
    )
}

useGLTF.preload('../../public/models/WawaOffice.glb')
